services:
  - type: web
    name: ig-backend
    runtime: node
    buildCommand: |
      echo "Downloading yt-dlp..."
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
      chmod +x yt-dlp
      echo "Checking file..."
      ls -l
      ./yt-dlp --version
      npm install
    startCommand: node server.js
